recent_topics/__init__.py
# -*- coding: utf-8 -*-
"""
    recent_topics
    ~~~~~~~~~~~~~~

    A recent_topics Plugin for FlaskBB.

    :copyright: (c) 2018 by Михаил Лебедев.
    :license: BSD License, see LICENSE for more details.
"""
import os

from flaskbb.utils.helpers import render_template

from .views import recent_topics_bp


__version__ = "0.0.1"


# connect the hooks
def flaskbb_load_migrations():
    return os.path.join(os.path.dirname(__file__), "migrations")


def flaskbb_load_translations():
    return os.path.join(os.path.dirname(__file__), "translations")


def flaskbb_load_blueprints(app):
    app.register_blueprint(recent_topics_bp, url_prefix="/recent_topics")


def flaskbb_tpl_navigation_after():
    return render_template("recent_topics_navlink.html")


SETTINGS = {}

recent_topics/views.py
# -*- coding: utf-8 -*-
"""
    recent_topics.views
    ~~~~~~~~~~~~~~~~~~~~

    This module contains the views for the
    recent_topics Plugin.

    :copyright: (c) 2018 by Михаил Лебедев.
    :license: BSD License, see LICENSE for more details.
"""
from flask import Blueprint, request
from flaskbb.utils.helpers import real, render_template
from flask_login import current_user
from flaskbb.extensions import db
from flaskbb.forum.models import Post, Topic, TopicsRead
from flaskbb.utils.settings import flaskbb_config


recent_topics_bp = Blueprint("recent_topics_bp", __name__, template_folder="templates")


@recent_topics_bp.route("/")
def index():
    page = request.args.get('page', 1, type=int)

    per_page = flaskbb_config['TOPICS_PER_PAGE']
    user = real(current_user)

    if user.is_authenticated:
        topics = Topic.query.\
            outerjoin(TopicsRead,
                      db.and_(TopicsRead.topic_id == Topic.id,
                              TopicsRead.user_id == user.id)).\
            outerjoin(Post, Topic.last_post_id == Post.id).\
            add_entity(Post).\
            add_entity(TopicsRead).\
            order_by(Topic.last_updated.desc()).\
            paginate(page, per_page, True)
    else:
        topics = Topic.query.\
            outerjoin(Post, Topic.last_post_id == Post.id).\
            add_entity(Post).\
            order_by(Topic.last_updated.desc()).\
            paginate(page, per_page, True)

        topics.items = [(topic, last_post, None)
                        for topic, last_post, in topics.items]

    return render_template(
        'recent_topics.html',
        active_forum_nav=False,
        topics=topics,
    )

recent_topics/templates/recent_topics.html
{% set page_title = _("Recent topics") %}
{% set active_forum_nav=False %}

{% extends theme("layout.html") %}
{% block content %}
{% from theme('macros.html') import render_pagination, topic_pages %}

<div class="forum-view">
    <ol class="breadcrumb flaskbb-breadcrumb">
        <li><a href="{{ url_for('forum.index') }}">{% trans %}Forum{% endtrans %}</a></li>
        <li class="active">{% trans %}Recent topics{% endtrans %}</li>
    </ol>

    <div class="row controls-row">
        <div class="pull-left">
            {{ render_pagination(topics, url_for('recent_topics_bp.index')) }}
        </div> <!-- end span pagination -->
    </div>

    <div class="panel forum-panel">
        <div class="panel-heading forum-head">
            {% trans %}Recent topics{% endtrans %}
        </div>

        <div class="panel-body forum-body">
            <div class="forum-meta">
                <div class="col-md-5 col-sm-5 col-xs-8 topic-name">{% trans %}Topic{% endtrans %}</div>
                <div class="col-md-2 col-sm-2 hidden-xs topic-stats">{% trans %}Posts{% endtrans %}</div>
                <div class="col-md-2 col-sm-2 hidden-xs topic-stats">{% trans %}Views{% endtrans %}</div>
                <div class="col-md-3 col-sm-3 col-xs-4 topic-last-post">{% trans %}Last Post{% endtrans %}</div>
            </div>

            {% for topic, last_post, topicread in topics.items %}
            <div class="row forum-row hover clearfix">

                <div class="col-md-5 col-sm-5 col-xs-8 topic-info">
                    <div class="row">
                        <div class="col-md-1 col-sm-2 col-xs-2 topic-status">
                        {% if topic.locked %}
                            <span class="fa fa-lock fa-fw topic-locked"></span>
                        {% elif topic.hidden %}
                            <span class="fa fa-user-secret"></span>
                        {% elif topic.important %}
                            {% if topic|topic_is_unread(topicread, current_user) %}
                                <span class="fa fa-star fa-fw topic-starred-unread"></span>
                            {% else %}
                                <span class="fa fa-star-o fa-fw topic-starred-read"></span>
                            {% endif %}
                        {% else %}
                            {% if topic|topic_is_unread(topicread, current_user) %}
                                <span class="fa fa-comment fa-fw topic-unread"></span>
                            {% else %}
                                <span class="fa fa-comment-o fa-fw topic-read"></span>
                            {% endif %}
                        {% endif %}
                        </div>
                        <div class="col-md-11 col-sm-10 col-xs-10">
                            <div class="topic-name">
                                <a href="{{ topic.first_unread(topicread, current_user) }}">{{ topic.title }}</a>
                                <!-- Topic Pagination -->
                                <span class="topic-pages">{{ topic_pages(topic, flaskbb_config["POSTS_PER_PAGE"]) }}</span>
                            </div>

                            <div class="topic-author">
                                {% trans %}by{% endtrans %}
                                {% if topic.user_id %}
                                    <a href="{{ topic.user.url }}">{{ topic.user.username }}</a>
                                {% else %}
                                    {{ topic.username }}
                                {% endif %}
                                {% trans %}in{% endtrans %}
                                <a href="{{ topic.forum.url }}">{{ topic.forum.title }}</a>
                            </div>

                            {% if topic.hidden %}
                            <div class="topic-author">
                                {{ gettext("Hidden on %(when)s  by %(who)s", who=topic.hidden_by.username, when=format_date(topic.hidden_at, '%b %d %Y'))}}
                            </div>
                            {% endif %}
                        </div>
                    </div>
                </div>
                <div class="col-md-2 col-sm-2 hidden-xs topic-stats">
                    {{ topic.post_count }}
                </div>

                <div class="col-md-2 col-sm-2 hidden-xs topic-stats">
                    {{ topic.views }}
                </div>

                <div class="col-md-3 col-sm-3 col-xs-4 topic-last-post">
                    <a href="{{ last_post.url }}">{{ last_post.date_created|time_since }}</a><br />

                    <div class="topic-author">
                        {% trans %}by{% endtrans %}
                        {% if last_post.user_id %}
                        <a href="{{ last_post.user.url }}">{{ last_post.user.username }}</a>
                        {% else %}
                        {{ last_post.username }}
                        {% endif %}
                    </div>
                </div>

            </div>  <!-- end forum-row -->
            {% else %}
            <div class="row forum-row clearfix">
                <div class="col-md-12 col-sm-12 co-xs-12">
                    {% trans %}No Topics.{% endtrans %}
                </div>
            </div> <!-- end forum-row -->
            {% endfor %}
        </div>
    </div>

</div>
{% endblock %}

recent_topics/templates/recent_topics_navlink.html
<li {% if 'recent_topics_bp.index' == request.endpoint %}class="active"{% endif %}>
    <a href="{{ url_for('recent_topics_bp.index') }}">
        <i class="fa fa-newspaper-o"></i> Recent topics
    </a>
</li>